name: esplotify_api
description: Music streaming API using YouTube
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  youtube_explode_dart: ^2.5.2
  mime: ^1.0.0

dev_dependencies:
  lints: ^2.0.0